const nome = prompt('Digite seu Nome Completo:')
document.body.innerHTML = `O seu nome é: ${nome}<br />`
document.body.innerHTML += `O seu nome tem letras <br />`
document.body.innerHTML += `A segunda letra do seu nome é: <br />`
document.body.innerHTML += `Qual o primeiro indice da letra a no seu nome?<br />`
document.body.innerHTML += `Qual o último indice da letra a no seu nome?<br />`
document.body.innerHTML += `As ultimas 3 letras do seu nome são: <br />`
document.body.innerHTML += `As palavras do seu nome são: <br />`
document.body.innerHTML += `Seu nome com letras maiúsculas: <br />`
document.body.innerHTML += `Seu nome com letras minúculas: <br />`