const nome = prompt('Digite seu Nome Completo:');
const nomeSemEspacos = nome.replace(/\s+/g, ''); // Remove todos os espaços 
const nomeLetras = nomeSemEspacos.length;// Conta o número de letras sem espaços
const segundaLetra = nome.charAt(1);// Pega a segunda letra do nome
const primeiroIndiceA = nome.indexOf('a');// Pega o primeiro índice da letra 'a'
const ultimoIndiceA = nome.lastIndexOf('a');// Pega o último índice da letra 'a'
const ultimasTresLetras = nome.slice(-3);// Pega as últimas 3 letras do nome
const palavras = nome.split(' ');// Divide o nome em palavras, separando por espaço
const nomeMaiusculo = nome.toUpperCase();// Converte o nome para letras maiúsculas
const nomeMinusculo = nome.toLowerCase();// Converte o nome para letras minúsculas
document.body.innerHTML = `O seu nome é: ${nome}<br />`
document.body.innerHTML += `O seu nome tem ${nomeLetras} letras <br />`
document.body.innerHTML += `A segunda letra do seu nome é: ${segundaLetra} <br />`
document.body.innerHTML += `Qual o primeiro indice da letra a no seu nome? ${primeiroIndiceA}<br />`
document.body.innerHTML += `Qual o último indice da letra a no seu nome ${ultimoIndiceA}<br />`
document.body.innerHTML += `As ultimas 3 letras do seu nome são: ${ultimasTresLetras} <br />`
document.body.innerHTML += `As palavras do seu nome são: ${palavras} <br />`
document.body.innerHTML += `Seu nome com letras maiúsculas:${nomeMaiusculo} <br />`
document.body.innerHTML += `Seu nome com letras minúculas: ${nomeMinusculo}<br />`